#!/bin/bash
# ===========================================
# Educational Platform - One-Click Installer
# ===========================================
# Run this ONCE to set up everything + create desktop launcher
# After that, just click the icon in your apps menu!
# ===========================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# Get the absolute path of this script's directory
INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$INSTALL_DIR/edu-platform"

echo ""
echo -e "${CYAN}${BOLD}"
cat << "EOF"
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║       🎓  Educational Platform - One-Click Installer         ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# ===========================================
# Check Docker
# ===========================================
echo -e "${BLUE}[1/6]${NC} Checking Docker..."

if ! command -v docker &> /dev/null; then
    echo -e "${RED}✗${NC} Docker not installed!"
    echo ""
    echo "Install Docker first:"
    echo "  Fedora: sudo dnf install docker docker-compose"
    echo "  Ubuntu: sudo apt install docker.io docker-compose"
    echo ""
    exit 1
fi

if ! docker info &> /dev/null; then
    echo -e "${YELLOW}⚠${NC} Docker daemon not running. Starting it..."
    sudo systemctl start docker
    sudo systemctl enable docker
fi

echo -e "${GREEN}✓${NC} Docker is ready"

# ===========================================
# Detect Resources
# ===========================================
echo -e "${BLUE}[2/6]${NC} Detecting system resources..."

TOTAL_RAM=$(free -g | awk '/^Mem:/{print $2}')
TOTAL_CORES=$(nproc)

echo -e "  RAM: ${BOLD}${TOTAL_RAM}GB${NC} | CPU: ${BOLD}${TOTAL_CORES} cores${NC}"

# Choose profile based on RAM
if [[ $TOTAL_RAM -lt 6 ]]; then
    PROFILE="minimal"
    SERVICES=""
    PROFILE_NAME="MINIMAL"
elif [[ $TOTAL_RAM -lt 12 ]]; then
    PROFILE="standard"
    SERVICES="maxima,jupyterhub,code-server,deepseek-proxy"
    PROFILE_NAME="STANDARD"
elif [[ $TOTAL_RAM -lt 24 ]]; then
    PROFILE="enhanced"
    SERVICES="maxima,jupyterhub,code-server,deepseek-proxy,rstudio,sagemath,grafana,prometheus"
    PROFILE_NAME="ENHANCED"
else
    PROFILE="full"
    SERVICES="maxima,jupyterhub,code-server,deepseek-proxy,rstudio,sagemath,grafana,prometheus,gitea,n8n,portainer"
    PROFILE_NAME="FULL"
fi

echo -e "  Profile: ${BOLD}${PROFILE_NAME}${NC}"

# ===========================================
# Generate Configuration
# ===========================================
echo -e "${BLUE}[3/6]${NC} Generating secure configuration..."

cd "$PLATFORM_DIR"

# Generate passwords
POSTGRES_PASS=$(openssl rand -base64 12 | tr -d "=+/")
MOODLE_PASS=$(openssl rand -base64 12 | tr -d "=+/")
JUPYTER_PASS=$(openssl rand -base64 12 | tr -d "=+/")
CODE_PASS=$(openssl rand -base64 12 | tr -d "=+/")

cat > .env << EOF
# Auto-generated by installer - $(date)
DOMAIN=localhost
COMPOSE_PROFILES=$SERVICES

# Moodle
MOODLE_USERNAME=admin
MOODLE_PASSWORD=$MOODLE_PASS
MOODLE_EMAIL=admin@example.com
MOODLE_SITE_NAME=Educational Platform

# Database
POSTGRES_PASSWORD=$POSTGRES_PASS
POSTGRES_MOODLE_DB=moodle_db
POSTGRES_JUPYTER_DB=jupyterhub_db
POSTGRES_GRAFANA_DB=grafana

# JupyterHub
JUPYTERHUB_ADMIN=admin
JUPYTERHUB_ADMIN_PASSWORD=$JUPYTER_PASS
JUPYTER_MEMORY_LIMIT=2G
JUPYTER_CPU_LIMIT=1.0

# Code Server
CODE_SERVER_PASSWORD=$CODE_PASS

# AI (optional - add your key)
DEEPSEEK_API_KEY=sk-placeholder
DEEPSEEK_PROXY_API_KEY=$CODE_PASS

# Maxima
MAXIMA_POOL_SIZE=3

# Optional services
RSTUDIO_PASSWORD=$CODE_PASS
SAGEMATH_TOKEN=$CODE_PASS
GRAFANA_USER=admin
GRAFANA_PASSWORD=$CODE_PASS
EOF

# Save credentials
cat > CREDENTIALS.txt << EOF
════════════════════════════════════════════════════
  🔐 YOUR LOGIN CREDENTIALS
════════════════════════════════════════════════════

🏠 DASHBOARD     http://localhost:8080

📚 MOODLE        http://localhost:8081
   User: admin
   Pass: $MOODLE_PASS

🔬 JUPYTERHUB    http://localhost:8000
   User: admin
   Pass: $JUPYTER_PASS

💻 CODE SERVER   http://localhost:8844
   Pass: $CODE_PASS

════════════════════════════════════════════════════
EOF

echo -e "${GREEN}✓${NC} Configuration saved to CREDENTIALS.txt"

# ===========================================
# Create Launcher Script
# ===========================================
echo -e "${BLUE}[4/6]${NC} Creating launcher..."

cat > "$INSTALL_DIR/eduplatform" << 'LAUNCHER'
#!/bin/bash
# Educational Platform Launcher

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$SCRIPT_DIR/edu-platform"
cd "$PLATFORM_DIR"

# Compose files
COMPOSE_CMD="docker compose -f docker-compose.yml -f docker-compose.override.yml"
if [[ -f "docker-compose.optional.yml" ]]; then
    source .env 2>/dev/null
    if [[ -n "$COMPOSE_PROFILES" ]]; then
        COMPOSE_CMD="$COMPOSE_CMD -f docker-compose.optional.yml"
    fi
fi

show_menu() {
    clear
    echo ""
    echo "╔════════════════════════════════════════╗"
    echo "║   🎓 Educational Platform              ║"
    echo "╠════════════════════════════════════════╣"
    echo "║  1) ▶  Start Platform                  ║"
    echo "║  2) ⏹  Stop Platform                   ║"
    echo "║  3) 🔄 Restart Platform                ║"
    echo "║  4) 📊 View Status                     ║"
    echo "║  5) 📜 View Logs                       ║"
    echo "║  6) 🌐 Open in Browser                 ║"
    echo "║  7) 🔑 Show Credentials                ║"
    echo "║  8) ❌ Exit                            ║"
    echo "╚════════════════════════════════════════╝"
    echo ""
}

start_platform() {
    echo "🚀 Starting platform..."
    $COMPOSE_CMD up -d
    echo ""
    echo "✓ Platform started!"
    echo ""
    echo "Access at: http://localhost:8080"
    echo ""
    read -p "Press Enter to continue..."
}

stop_platform() {
    echo "⏹ Stopping platform..."
    $COMPOSE_CMD down
    echo "✓ Platform stopped!"
    read -p "Press Enter to continue..."
}

restart_platform() {
    echo "🔄 Restarting platform..."
    $COMPOSE_CMD restart
    echo "✓ Platform restarted!"
    read -p "Press Enter to continue..."
}

show_status() {
    echo "📊 Service Status:"
    echo ""
    $COMPOSE_CMD ps
    echo ""
    read -p "Press Enter to continue..."
}

show_logs() {
    echo "📜 Logs (Ctrl+C to exit):"
    $COMPOSE_CMD logs -f --tail=50
}

open_browser() {
    if command -v xdg-open &> /dev/null; then
        xdg-open "http://localhost:8080" 2>/dev/null &
    elif command -v open &> /dev/null; then
        open "http://localhost:8080"
    else
        echo "Open http://localhost:8080 in your browser"
    fi
    echo "🌐 Opening browser..."
    sleep 1
}

show_credentials() {
    echo ""
    cat "$PLATFORM_DIR/CREDENTIALS.txt"
    echo ""
    read -p "Press Enter to continue..."
}

# Main loop
while true; do
    show_menu
    read -p "Choose [1-8]: " choice

    case $choice in
        1) start_platform ;;
        2) stop_platform ;;
        3) restart_platform ;;
        4) show_status ;;
        5) show_logs ;;
        6) open_browser ;;
        7) show_credentials ;;
        8) echo "Goodbye!"; exit 0 ;;
        *) echo "Invalid choice" ;;
    esac
done
LAUNCHER

chmod +x "$INSTALL_DIR/eduplatform"
echo -e "${GREEN}✓${NC} Launcher created: ${BOLD}./eduplatform${NC}"

# ===========================================
# Create Desktop Icon
# ===========================================
echo -e "${BLUE}[5/6]${NC} Creating desktop shortcut..."

DESKTOP_DIR="$HOME/.local/share/applications"
mkdir -p "$DESKTOP_DIR"

# Create icon (simple base64 encoded PNG or use system icon)
ICON_PATH="$INSTALL_DIR/edu-platform/icon.png"

# Create a simple SVG icon if no icon exists
cat > "$INSTALL_DIR/edu-platform/icon.svg" << 'ICON'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <circle cx="50" cy="50" r="45" fill="#2563eb"/>
  <text x="50" y="65" font-size="40" fill="white" text-anchor="middle" font-family="Arial">🎓</text>
</svg>
ICON

# Create .desktop file
cat > "$DESKTOP_DIR/edu-platform.desktop" << EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Educational Platform
Comment=Moodle, JupyterHub, Code Server
Icon=$INSTALL_DIR/edu-platform/icon.svg
Exec=gnome-terminal -- $INSTALL_DIR/eduplatform
Terminal=false
Categories=Education;Development;
Keywords=moodle;jupyter;education;learning;
EOF

# Also create on Desktop if it exists
if [[ -d "$HOME/Desktop" ]]; then
    cp "$DESKTOP_DIR/edu-platform.desktop" "$HOME/Desktop/"
    chmod +x "$HOME/Desktop/edu-platform.desktop"
    # Mark as trusted on GNOME
    gio set "$HOME/Desktop/edu-platform.desktop" metadata::trusted true 2>/dev/null || true
fi

# Update desktop database
update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true

echo -e "${GREEN}✓${NC} Desktop shortcut created!"

# ===========================================
# Pull Docker Images
# ===========================================
echo -e "${BLUE}[6/6]${NC} Downloading Docker images (this takes a few minutes)..."

cd "$PLATFORM_DIR"

COMPOSE_CMD="docker compose -f docker-compose.yml -f docker-compose.override.yml"
if [[ -n "$SERVICES" ]]; then
    COMPOSE_CMD="$COMPOSE_CMD -f docker-compose.optional.yml"
fi

$COMPOSE_CMD pull 2>&1 | grep -E "(Pulling|Downloaded|Pull complete)" || true

echo -e "${GREEN}✓${NC} Images downloaded!"

# ===========================================
# Done!
# ===========================================
echo ""
echo -e "${GREEN}${BOLD}"
cat << "EOF"
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║       ✅  Installation Complete!                             ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

echo -e "${BOLD}How to use:${NC}"
echo ""
echo -e "  ${CYAN}Option 1:${NC} Click ${BOLD}'Educational Platform'${NC} in your apps menu"
echo ""
echo -e "  ${CYAN}Option 2:${NC} Run ${BOLD}./eduplatform${NC} from terminal"
echo ""
echo -e "${BOLD}Your credentials are saved in:${NC}"
echo "  $PLATFORM_DIR/CREDENTIALS.txt"
echo ""

read -p "Start the platform now? [Y/n] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    "$INSTALL_DIR/eduplatform"
fi
