@echo off
REM ===========================================
REM Educational Platform - One-Click Installer (Windows)
REM ===========================================
REM Run this ONCE to set up everything + create desktop shortcut
REM After that, just double-click the shortcut!
REM ===========================================

setlocal enabledelayedexpansion

title Educational Platform Installer

cls
echo.
echo ╔═══════════════════════════════════════════════════════════════╗
echo ║                                                               ║
echo ║       🎓  Educational Platform - One-Click Installer         ║
echo ║                                                               ║
echo ╚═══════════════════════════════════════════════════════════════╝
echo.

REM Get script directory
set "INSTALL_DIR=%~dp0"
set "INSTALL_DIR=%INSTALL_DIR:~0,-1%"
set "PLATFORM_DIR=%INSTALL_DIR%\edu-platform"

REM ===========================================
REM Check Docker
REM ===========================================
echo [1/6] Checking Docker...

docker --version >nul 2>&1
if errorlevel 1 (
    echo.
    echo ERROR: Docker is not installed!
    echo.
    echo Please install Docker Desktop from:
    echo   https://www.docker.com/products/docker-desktop
    echo.
    pause
    exit /b 1
)

docker info >nul 2>&1
if errorlevel 1 (
    echo.
    echo ERROR: Docker Desktop is not running!
    echo Please start Docker Desktop and run this again.
    echo.
    pause
    exit /b 1
)

echo OK - Docker is ready
echo.

REM ===========================================
REM Detect RAM and choose profile
REM ===========================================
echo [2/6] Detecting system resources...

for /f "tokens=2 delims==" %%i in ('wmic computersystem get TotalPhysicalMemory /value ^| find "="') do set RAM_BYTES=%%i
set /a RAM_GB=!RAM_BYTES:~0,-9!

echo   RAM: !RAM_GB! GB

if !RAM_GB! LSS 6 (
    set "PROFILE=minimal"
    set "SERVICES="
    set "PROFILE_NAME=MINIMAL"
) else if !RAM_GB! LSS 12 (
    set "PROFILE=standard"
    set "SERVICES=maxima,jupyterhub,code-server,deepseek-proxy"
    set "PROFILE_NAME=STANDARD"
) else if !RAM_GB! LSS 24 (
    set "PROFILE=enhanced"
    set "SERVICES=maxima,jupyterhub,code-server,deepseek-proxy,rstudio,sagemath,grafana,prometheus"
    set "PROFILE_NAME=ENHANCED"
) else (
    set "PROFILE=full"
    set "SERVICES=maxima,jupyterhub,code-server,deepseek-proxy,rstudio,sagemath,grafana,prometheus,gitea,n8n,portainer"
    set "PROFILE_NAME=FULL"
)

echo   Profile: !PROFILE_NAME!
echo.

REM ===========================================
REM Generate Configuration
REM ===========================================
echo [3/6] Generating secure configuration...

cd /d "%PLATFORM_DIR%"

REM Generate random passwords
set "CHARS=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
set "MOODLE_PASS=Moodle!%RANDOM%%RANDOM%"
set "JUPYTER_PASS=Jupyter!%RANDOM%%RANDOM%"
set "CODE_PASS=Code!%RANDOM%%RANDOM%"
set "DB_PASS=DB!%RANDOM%%RANDOM%"

REM Create .env file
(
    echo # Auto-generated by installer
    echo DOMAIN=localhost
    echo COMPOSE_PROFILES=!SERVICES!
    echo.
    echo MOODLE_USERNAME=admin
    echo MOODLE_PASSWORD=!MOODLE_PASS!
    echo MOODLE_EMAIL=admin@example.com
    echo MOODLE_SITE_NAME=Educational Platform
    echo.
    echo POSTGRES_PASSWORD=!DB_PASS!
    echo POSTGRES_MOODLE_DB=moodle_db
    echo POSTGRES_JUPYTER_DB=jupyterhub_db
    echo POSTGRES_GRAFANA_DB=grafana
    echo.
    echo JUPYTERHUB_ADMIN=admin
    echo JUPYTERHUB_ADMIN_PASSWORD=!JUPYTER_PASS!
    echo JUPYTER_MEMORY_LIMIT=2G
    echo JUPYTER_CPU_LIMIT=1.0
    echo.
    echo CODE_SERVER_PASSWORD=!CODE_PASS!
    echo.
    echo DEEPSEEK_API_KEY=sk-placeholder
    echo DEEPSEEK_PROXY_API_KEY=!CODE_PASS!
    echo MAXIMA_POOL_SIZE=3
    echo.
    echo RSTUDIO_PASSWORD=!CODE_PASS!
    echo SAGEMATH_TOKEN=!CODE_PASS!
    echo GRAFANA_USER=admin
    echo GRAFANA_PASSWORD=!CODE_PASS!
) > .env

REM Create credentials file
(
    echo ════════════════════════════════════════════════════
    echo   YOUR LOGIN CREDENTIALS
    echo ════════════════════════════════════════════════════
    echo.
    echo DASHBOARD     http://localhost:8080
    echo.
    echo MOODLE        http://localhost:8081
    echo    User: admin
    echo    Pass: !MOODLE_PASS!
    echo.
    echo JUPYTERHUB    http://localhost:8000
    echo    User: admin
    echo    Pass: !JUPYTER_PASS!
    echo.
    echo CODE SERVER   http://localhost:8844
    echo    Pass: !CODE_PASS!
    echo.
    echo ════════════════════════════════════════════════════
) > CREDENTIALS.txt

echo OK - Credentials saved
echo.

REM ===========================================
REM Create Launcher Script
REM ===========================================
echo [4/6] Creating launcher...

(
    echo @echo off
    echo setlocal enabledelayedexpansion
    echo title Educational Platform
    echo cd /d "%PLATFORM_DIR%"
    echo.
    echo :MENU
    echo cls
    echo.
    echo ╔════════════════════════════════════════╗
    echo ║   Educational Platform                 ║
    echo ╠════════════════════════════════════════╣
    echo ║  1^) Start Platform                     ║
    echo ║  2^) Stop Platform                      ║
    echo ║  3^) Restart Platform                   ║
    echo ║  4^) View Status                        ║
    echo ║  5^) View Logs                          ║
    echo ║  6^) Open in Browser                    ║
    echo ║  7^) Show Credentials                   ║
    echo ║  8^) Exit                               ║
    echo ╚════════════════════════════════════════╝
    echo.
    echo.
    echo set /p choice="Choose [1-8]: "
    echo.
    echo if "%%choice%%"=="1" goto START
    echo if "%%choice%%"=="2" goto STOP
    echo if "%%choice%%"=="3" goto RESTART
    echo if "%%choice%%"=="4" goto STATUS
    echo if "%%choice%%"=="5" goto LOGS
    echo if "%%choice%%"=="6" goto BROWSER
    echo if "%%choice%%"=="7" goto CREDS
    echo if "%%choice%%"=="8" exit
    echo goto MENU
    echo.
    echo :START
    echo echo Starting platform...
    echo docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.optional.yml up -d
    echo echo.
    echo echo Platform started! Access at http://localhost:8080
    echo pause
    echo goto MENU
    echo.
    echo :STOP
    echo echo Stopping platform...
    echo docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.optional.yml down
    echo echo Platform stopped.
    echo pause
    echo goto MENU
    echo.
    echo :RESTART
    echo echo Restarting platform...
    echo docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.optional.yml restart
    echo echo Platform restarted.
    echo pause
    echo goto MENU
    echo.
    echo :STATUS
    echo docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.optional.yml ps
    echo.
    echo pause
    echo goto MENU
    echo.
    echo :LOGS
    echo docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.optional.yml logs -f --tail=50
    echo goto MENU
    echo.
    echo :BROWSER
    echo start http://localhost:8080
    echo goto MENU
    echo.
    echo :CREDS
    echo.
    echo type CREDENTIALS.txt
    echo.
    echo pause
    echo goto MENU
) > "%INSTALL_DIR%\EduPlatform.bat"

echo OK - Launcher created
echo.

REM ===========================================
REM Create Desktop Shortcut
REM ===========================================
echo [5/6] Creating desktop shortcut...

REM Create VBS script to make shortcut
(
    echo Set oWS = WScript.CreateObject^("WScript.Shell"^)
    echo sLinkFile = oWS.SpecialFolders^("Desktop"^) ^& "\Educational Platform.lnk"
    echo Set oLink = oWS.CreateShortcut^(sLinkFile^)
    echo oLink.TargetPath = "%INSTALL_DIR%\EduPlatform.bat"
    echo oLink.WorkingDirectory = "%PLATFORM_DIR%"
    echo oLink.Description = "Educational Platform - Moodle, JupyterHub, Code Server"
    echo oLink.IconLocation = "shell32.dll,47"
    echo oLink.Save
) > "%TEMP%\CreateShortcut.vbs"

cscript //nologo "%TEMP%\CreateShortcut.vbs"
del "%TEMP%\CreateShortcut.vbs"

echo OK - Desktop shortcut created
echo.

REM ===========================================
REM Pull Docker Images
REM ===========================================
echo [6/6] Downloading Docker images (this takes a few minutes)...
echo.

cd /d "%PLATFORM_DIR%"

if "!SERVICES!"=="" (
    docker compose -f docker-compose.yml -f docker-compose.override.yml pull
) else (
    docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.optional.yml pull
)

echo.
echo OK - Images downloaded
echo.

REM ===========================================
REM Done!
REM ===========================================
echo.
echo ╔═══════════════════════════════════════════════════════════════╗
echo ║                                                               ║
echo ║       Installation Complete!                                  ║
echo ║                                                               ║
echo ╚═══════════════════════════════════════════════════════════════╝
echo.
echo How to use:
echo.
echo   Option 1: Double-click "Educational Platform" on your Desktop
echo.
echo   Option 2: Run EduPlatform.bat
echo.
echo Your credentials are saved in:
echo   %PLATFORM_DIR%\CREDENTIALS.txt
echo.

set /p START_NOW="Start the platform now? [Y/n] "
if /i not "!START_NOW!"=="n" (
    call "%INSTALL_DIR%\EduPlatform.bat"
)

endlocal
